#!/usr/bin/env python3
"""Build runs/t45/sample_data.dat from the measured bonded fits of the theta0 = 45 campaign -- no hand-typed numbers.
Source (grant repo, prelim/results):  cg_bonded_fits_t45_grd_k20.csv   bonds [kT/a^2, a] and bends K_rad [kT/rad^2]
                                       cg_steric_coil_fit_t45_k20.csv   gaussian coil core A [kT], sigma [a]
                                       cg_block_realized_geometry.csv   block axial length and screw radius [a]
RECIPE = the one the t100 file follows: each mirror-symmetric class is the MEAN of its members
  bonds  CC | CH = (CL, CR) | HH = (LL, RR) | RL = LR
  bends  CCC | CCH = (CCL, CCR) | CHC = (CLC, CRC) | CHH = (CLL, CRR) | CRL = (CLR, CRL) | HCH = (LCL, RCR) | RCL = LCR
         HHH = (LLL, RRR) | RRL = (LLR, LRR) | RLR = (LRL, RLR);   theta0 = 180 deg for every class (as in t100).
UNITS: every length is in bead diameters a, so the MC length unit IS a and hf_len = 1.
With --check-t100 the same recipe is applied to cg_bonded_fits_grd_k20.csv and printed beside runs/t100/sample_data.dat."""
import csv, os, sys
R = "/home/reyhaneh/Documents/Helical_polymer_grant/prelim/results"
HERE = os.path.dirname(os.path.abspath(__file__))
# CONVENTION (fixed 2026-09-23): the fits report U = K (x - x0)^2 while the code evaluates
# 1/2 k (x - x0)^2, so the file must carry k = 2 K (bonds and bends); before the fix k = K was written
# and every bond and bend was a factor 2 softer than measured (bond std 0.225 a vs 0.159 a for RR at t45).
KFAC = 2.0
BOND = {"CC": ["CC"], "CH": ["CL", "CR"], "HH": ["LL", "RR"], "RL": ["LR"]}
BEND = {"CCC": ["CCC"], "CCH": ["CCL", "CCR"], "CHC": ["CLC", "CRC"], "CHH": ["CLL", "CRR"], "CRL": ["CLR", "CRL"], "HCH": ["LCL", "RCR"],
        "RCL": ["LCR"], "HHH": ["LLL", "RRR"], "RRL": ["LLR", "LRR"], "RLR": ["LRL", "RLR"]}
def recipe(fits_csv):
    rows = {(r["kind"], r["key"]): r for r in csv.DictReader(open(fits_csv))}
    mean = lambda kind, keys, col: sum(float(rows[(kind, k)][col]) for k in keys) / len(keys)
    return ({c: (mean("bond", ks, "x0"), mean("bond", ks, "K")) for c, ks in BOND.items()},
            {c: mean("bend", ks, "K_rad") for c, ks in BEND.items()},
            {c: max(float(rows[("bond", k)]["rms_kT"]) for k in ks) for c, ks in BOND.items()})

if "--check-t100" in sys.argv:
    bond, bend, rms = recipe(f"{R}/cg_bonded_fits_grd_k20.csv"); cur = {}
    for l in open(f"{HERE}/../t100/sample_data.dat"):
        l = l.split("#")[0]
        if "=" in l: k, v = [x.strip() for x in l.split("=", 1)]; cur[k] = v.split()[0]
    print("t100: recipe applied to cg_bonded_fits_grd_k20.csv   vs   runs/t100/sample_data.dat")
    for c in BOND: print(f"  bond {c}: len {bond[c][0]:.3f} vs {cur['bond_len_' + c]:>5s}    k = 2K {KFAC * bond[c][1]:7.3f} vs {cur['k_bond_' + c]:>6s}    (fit rms {rms[c]:.3f} kT)")
    for c in BEND:
        d = 100 * (float(cur["kappa_" + c]) - KFAC * bend[c]) / (KFAC * bend[c])
        print(f"  bend {c}: kappa = 2K {KFAC * bend[c]:6.3f} vs {cur['kappa_' + c]:>5s}   ({d:+6.1f} %)" + ("   <-- differs by more than 10 %" if abs(d) > 10 else ""))
    sys.exit()

# --geometry t100 (2026-09-23): the t100 file was hand-typed before and carried kappa_HCH = 0.59 (the t45 value; the t100
# fit gives 0.30) and kappa_CHH 23 % high -- now BOTH files come from this recipe.  The RL bond takes the HH values when
# the LR fit is poor (rms > 0.1 kT: t100, 0.20 kT), the user's "RL treated as HH"; the coil core (Gaussian, from the
# t45 coil fit) is the same for both geometries -- coil blocks carry no helical stiffness.
GEOM = "t100" if "--geometry" in sys.argv and sys.argv[sys.argv.index("--geometry") + 1] == "t100" else "t45"
FITS = {"t45": "cg_bonded_fits_t45_grd_k20.csv", "t100": "cg_bonded_fits_grd_k20.csv"}[GEOM]
THETA0 = {"t45": 45, "t100": 100}[GEOM]
OUT = os.path.join(HERE, "..", GEOM, "sample_data.dat")
bond, bend, rms = recipe(f"{R}/{FITS}")
if rms["RL"] > 0.1:
    bond["RL"] = bond["HH"]
coil = next(r for r in csv.DictReader(open(f"{R}/cg_steric_coil_fit_t45_k20.csv")) if r["form"] == "gaussian")
geo = [r for r in csv.DictReader(open(f"{R}/cg_block_realized_geometry.csv")) if r["campaign"] == GEOM]
L = sum(float(r["axial_len_screw"]) for r in geo) / len(geo); rad = sum(float(r["screw_radius"]) for r in geo) / len(geo)
out = [f"# Zimm-Bragg chain, theta0 = {THETA0} campaign.  GENERATED by runs/t45/make_sample_data.py --geometry {GEOM} from the measured bonded fits ({FITS}) -- do not edit by hand.",
       "# k_bond_* and kappa_* are TWICE the fitted K (fit: U = K (x - x0)^2; code: U = 1/2 k (x - x0)^2).",
       "# All lengths in bead diameters a (the MC length unit is a: hf_len = 1).  theta0_* carry the 'deg' suffix (the parser reads radians otherwise).",
       "N           = 200", "init        = walk", "",
       "# ---- bonds: class = mean of its mirror members (CH = CL,CR; HH = LL,RR; RL = LR) ----"]
for c in BOND: out += [f"bond_len_{c} = {bond[c][0]:.4f}", f"k_bond_{c}   = {KFAC * bond[c][1]:.4f}"]
out += ["", "# ---- bends: kappa = 2 x mean K_rad of the class members, theta0 = 180 deg (as in the t100 file) ----"]
for c in BEND: out += [f"kappa_{c}   = {KFAC * bend[c]:.4f}", f"theta0_{c} = 180 deg"]
out += ["", "# ---- nearest-neighbour state energies: placeholders, set by the scan generator ----", "J0          = 1", "J1          = 0", "J2          = 1", "",
        "kT          = 1.0", "n_equil     = 30000", "n_sweeps    = 200000", "max_disp    = 1.0", "seed        = 450001", "",
        "log_every   = 100", "dump_every  = 1000", "out_prefix  = out/sample",
        "nb_type = gauss", f"nb_A = {float(coil['A_kT']):.4f}", f"nb_sigma = {float(coil['sigma_a']):.4f}",
        "nb_hh = fit", f"hf_theta0 = {THETA0}", "hf_len = 1.0", "hf_clamp = 1",
        f"rod_L = {L:.4f}      # measured block axial length [a]; with nb_hh = fit this is used for the trajectory dump only",
        f"rod_r = {rad:.4f}      # measured screw radius [a]; trajectory dump only", "n_pivot = 4", "n_flip = 4"]
open(OUT, "w").write("\n".join(out) + "\n")
print("wrote", os.path.normpath(OUT));  print("  worst bond-fit rms per class [kT]: " + ", ".join(f"{c} {rms[c]:.3f}" for c in BOND))
